config/routes.rb
Rails.application.routes.draw do

  get 'acquisto/index'
  get 'carrello/index'
  get 'login/index'
  get 'home/index'


  resources :games
  resources :categories
  resources :utents
  resources :orders
  resources :lines

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :games
    validates :nome_cat, presence: true, length: { minimum: 5 }
    validates :descr, presence: true,  length: { maximum: 300 }
    validates :img1, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :category
  has_many :lines
  validates :nome, presence: true, length: { minimum: 5 }
  validates :descr, presence: true,  length: { maximum: 300 }
  validates :img1, presence: true
  validates :img2, presence: true
  validates :img3, presence: true
  validates :prezzo, presence: true

end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :game
  validates :quantita, presence: true
  validates :prezzo, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  has_one :line
  belongs_to :utent
  validates :data, presence: true
end

app/models/utent.rb
class Utent < ApplicationRecord
    has_many :orders
    has_many :lines, through: :orders
    validates :email, presence: true, length: { minimum: 11 }
    validates :password, presence: true,  length: { minimum: 8 }

end

app/controllers/carrello_controller.rb
class CarrelloController < ApplicationController
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

 def create
   @game = Game.new(game_params)

  if @game.save
    redirect_to @game
  else
    render 'new'
  end
 end

def update
 @game = Game.find(params[:id])

 if @game.update(game_params)
   redirect_to @game
 else
   render 'edit'
 end
end

def destroy
  @game = Game.find(params[:id])
  @game.destroy

  redirect_to games_path
end

private
  def game_params
    params.require(:game).permit(:nome,:descr,:category_id,:img1,:img2,:img3,:prezzo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @lines = Line.all
  end

  def show
    @line = Line.find(params[:id])
  end

  def new
    @line = Line.new
  end

  def edit
    @line = Line.find(params[:id])
  end

 def create
   @line = Line.new(line_params)

  if @line.save
    redirect_to @line
  else
    render 'new'
  end
 end

def update
 @line = Line.find(params[:id])

 if @line.update(line_params)
   redirect_to @line
 else
   render 'edit'
 end
end

def destroy
  @line = Line.find(params[:id])
  @line.destroy

  redirect_to lines_path
end

private
  def line_params
    params.require(:line).permit(:order_id,:game_id,:quantita,:prezzo)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

 def create
   @order = Order.new(order_params)

  if @order.save
    redirect_to @order
  else
    render 'new'
  end
 end

def update
 @order = Order.find(params[:id])

 if @order.update(order_params)
   redirect_to @order
 else
   render 'edit'
 end
end

def destroy
  @order = Order.find(params[:id])
  @order.destroy

  redirect_to orders_path
end

private
  def order_params
    params.require(:order).permit(:data,:utent_id)
  end
end

app/helpers/acquisto_helper.rb
module AcquistoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carrello_helper.rb
module CarrelloHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/utents_helper.rb
module UtentsHelper
end

app/views/carrello/index.html.erb
  <div class="row with_zero_margin">
    <div class="col-sm-3 sfondo_bordo2"></div>
    <div class="col-sm-6">
      <div class="contain">
        <h1>Carrello</h1>
        <div class="row" style="padding-bottom:3vh;">
          <div class="col-sm-3 offset-sm-1">
            <img class="rounded-circle bordo" src="/assets/tooks.jpg" width="100" height="100">
          </div>
          <div class="col-sm-8">
            <div class="gioco_acquisto">
              <h6 style="padding-top:1.5vh;"><strong>Nome:</strong> Tooks</h6>
              <h6><strong>Categoria:</strong> Strategia</h6>
              <h6><strong>Prezzo:</strong> 50,00€</h6>
            </div>
          </div>
        </div>
        <div class="row" style="padding-bottom:3vh;">
          <div class="col-sm-3 offset-sm-1">
            <img class="rounded-circle bordo" src="/assets/tooks.jpg" width="100" height="100">
          </div>
          <div class="col-sm-8">
            <div class="gioco_acquisto">
              <h6 style="padding-top:1.5vh;"><strong>Nome:</strong> Tooks</h6>
              <h6><strong>Categoria:</strong> Strategia</h6>
              <h6><strong>Prezzo:</strong> 69.99€</h6>
            </div>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="totale">
          <h4><strong>Prezzo totale - </strong> 69.99€</h4>
        </div>

        <div class="acquisto">
          <h5><%= link_to 'Procedi con l\'acquisto', acquisto_index_path %></h5>
        </div>


      </div>
    </div>
    <div class="col-sm-3 sfondo_bordo2"></div>
  </div>