config/routes.rb
Rails.application.routes.draw do

  get 'acquisto/index'
  get 'carrello/index'
  get 'login/index'
  get 'home/index'


  resources :games
  resources :categories
  resources :utents
  resources :orders
  resources :lines

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :games
    validates :nome_cat, presence: true, length: { minimum: 5 }
    validates :descr, presence: true,  length: { maximum: 300 }
    validates :img1, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :category
  has_many :lines
  validates :nome, presence: true, length: { minimum: 5 }
  validates :descr, presence: true,  length: { maximum: 300 }
  validates :img1, presence: true
  validates :img2, presence: true
  validates :img3, presence: true
  validates :prezzo, presence: true

end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :game
  validates :quantita, presence: true
  validates :prezzo, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  has_one :line
  belongs_to :utent
  validates :data, presence: true
end

app/models/utent.rb
class Utent < ApplicationRecord
    has_many :orders
    has_many :lines, through: :orders
    validates :email, presence: true, length: { minimum: 11 }
    validates :password, presence: true,  length: { minimum: 8 }

end

app/controllers/acquisto_controller.rb
class AcquistoController < ApplicationController
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

 def create
   @game = Game.new(game_params)

  if @game.save
    redirect_to @game
  else
    render 'new'
  end
 end

def update
 @game = Game.find(params[:id])

 if @game.update(game_params)
   redirect_to @game
 else
   render 'edit'
 end
end

def destroy
  @game = Game.find(params[:id])
  @game.destroy

  redirect_to games_path
end

private
  def game_params
    params.require(:game).permit(:nome,:descr,:category_id,:img1,:img2,:img3,:prezzo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @lines = Line.all
  end

  def show
    @line = Line.find(params[:id])
  end

  def new
    @line = Line.new
  end

  def edit
    @line = Line.find(params[:id])
  end

 def create
   @line = Line.new(line_params)

  if @line.save
    redirect_to @line
  else
    render 'new'
  end
 end

def update
 @line = Line.find(params[:id])

 if @line.update(line_params)
   redirect_to @line
 else
   render 'edit'
 end
end

def destroy
  @line = Line.find(params[:id])
  @line.destroy

  redirect_to lines_path
end

private
  def line_params
    params.require(:line).permit(:order_id,:game_id,:quantita,:prezzo)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

 def create
   @order = Order.new(order_params)

  if @order.save
    redirect_to @order
  else
    render 'new'
  end
 end

def update
 @order = Order.find(params[:id])

 if @order.update(order_params)
   redirect_to @order
 else
   render 'edit'
 end
end

def destroy
  @order = Order.find(params[:id])
  @order.destroy

  redirect_to orders_path
end

private
  def order_params
    params.require(:order).permit(:data,:utent_id)
  end
end

app/controllers/utents_controller.rb
class UtentsController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @utents = Utent.all
  end

  def show
    @utent = Utent.find(params[:id])
  end

  def new
    @utent = Utent.new
  end

  def edit
    @utent = Utent.find(params[:id])
  end

 def create
   @utent = Utent.new(utent_params)

  if @utent.save
    redirect_to @utent
  else
    render 'new'
  end
 end

def update
 @utent = Utent.find(params[:id])

 if @utent.update(utent_params)
   redirect_to @utent
 else
   render 'edit'
 end
end

def destroy
  @utent = Utent.find(params[:id])
  @utent.destroy

  redirect_to utents_path
end

private
  def utent_params
    params.require(:utent).permit(:email,:password)
  end
end

app/helpers/acquisto_helper.rb
module AcquistoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carrello_helper.rb
module CarrelloHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/utents_helper.rb
module UtentsHelper
end

app/views/games/_form.html.erb
<%= form_with model: @game, local: true do |form| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row with_zero_margin">

    <div class="col-sm-4">
      <p>
        <%= form.label :nome %><br>
        <%= form.text_field :nome %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :descrizione %><br>
        <%= form.text_area :descr %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :categoria %><br>
        <%= form.text_area :category_id %> <!-- form.field -->
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :immagine1 %><br>
        <%= form.text_area :img1 %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :immagine2 %><br>
        <%= form.text_area :img2 %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :immagine3 %><br>
        <%= form.text_area :img3 %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :prezzo %><br>
        <%= form.text_area :prezzo %>
      </p>
    </div>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>

app/views/games/edit.html.erb
<%= form_with(model: @game, local: true) do |form| %>

<% end %>

<div class="new">
  <h1>Modifica il gioco </h1>

  <%= render 'form' %>
</div>

<div class="link"><strong>
  <%= link_to 'Giochi', games_path  %>
  </strong>
</div>

app/views/games/index.html.erb
<div class="new">
  <h1>Giochi</h1>

  <table>
    <tr>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th>Categoria</th>
      <th>Immagine1</th>
      <th>Immagine2</th>
      <th>Immagien3</th>
      <th>Prezzo</th>
      <th colspan="3"></th>
    </tr>

    <% @games.each do |game| %>
      <tr>
        <td><%= game.nome %></td>
        <td><%= game.descr %></td>
        <td><%= game.category_id %></td>
        <td><%= game.img1 %></td>
        <td><%= game.img2 %></td>
        <td><%= game.img3 %></td>
        <td><%= game.prezzo %></td>
        <td><%= link_to 'Show', game_path(game) %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game_path(game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

</div>
<div class="link">
  <div class="row">
    <div class="col-sm-9">
      <strong>
        <%= link_to 'Giochi', controller: 'games' %>
        <%= link_to 'Categorie', categories_path %>
        <%= link_to 'Righe di ordine', lines_path %>
        <%= link_to 'Ordini', orders_path %>
        <%= link_to 'Utenti', utents_path %>

        <%= link_to 'Nuovo Gioco', new_game_path %>
      </strong>
    </div>
    <div class="col-sm-3">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">2</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">3</a></li>
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<%= form_with scope: :game, url: games_path, local: true do |form| %>

<% end %>

<div class="new">
  <h1>Aggiungi un gioco</h1>

  <%= render 'form' %>

</div>


<div class="link"><strong>
  <%= link_to 'Giochi', games_path  %>
  </strong>
</div>

app/views/games/show.html.erb
<div class="new">

  <p>
    <strong>Nome:</strong>
    <%= @game.nome %>
  </p>

  <p>
    <strong>Descrizione:</strong>
    <%= @game.descr %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= @game.category_id %>
  </p>

  <p>
    <strong>Immagine1:</strong>
    <%= @game.img1 %>
  </p>

  <p>
    <strong>Immagine2:</strong>
    <%= @game.img2%>
  </p>

  <p>
    <strong>Immagine3:</strong>
    <%= @game.img3 %>
  </p>

  <p>
    <strong>Prezzo:</strong>
    <%= @game.prezzo %>
  </p>


</div>

<div class="link"><strong>
  <%= link_to 'Giochi', games_path  %>
  <%= link_to 'Nuovo gioco', new_game_path %>
  <%= link_to 'Modifica il gioco', edit_game_path(@game) %>
  <%= link_to 'Elimina il gioco', game_path(@game),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </strong>
</div>

app/views/lines/_form.html.erb
<%= form_with model: @line, local: true do |form| %>

  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@line.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @line.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row with_zero_margin">

    <div class="col-sm-3">
      <p>
        <%= form.label :ordine %><br>
        <%= form.text_field :order_id %>
      </p>
    </div>
    
    <div class="col-sm-3">
      <p>
        <%= form.label :gioco %><br>
        <%= form.text_area :game_id %>
      </p>
    </div>

    <div class="col-sm-3">
      <p>
        <%= form.label :quantita %><br>
        <%= form.text_area :quantita %>
      </p>
    </div>

    <div class="col-sm-3">
      <p>
        <%= form.label :prezzo %><br>
        <%= form.text_area :prezzo %>
      </p>
    </div>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>

app/views/lines/edit.html.erb
<%= form_with(model: @line, local: true) do |form| %>

<% end %>

<div class="new">
  <h1>Modifica la riga di ordine </h1>

  <%= render 'form' %>
</div>

<div class="link"><strong>
  <%= link_to 'Righe di ordine', lines_path  %>
  </strong>
</div>

app/views/lines/index.html.erb
<div class="new">
  <h1>Righe di ordine</h1>

  <table>
    <tr>
      <th>Ordine</th>
      <th>Gioco</th>
      <th>Quantita</th>
      <th>Prezzo</th>
      <th colspan="3"></th>
    </tr>

    <% @lines.each do |line| %>
      <tr>
        <td><%= line.order_id %></td>
        <td><%= line.game_id %></td>
        <td><%= line.quantita %></td>
        <td><%= line.prezzo %></td>
        <td><%= link_to 'Show', line_path(line) %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line_path(line),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

</div>
<div class="link">
  <div class="row">
    <div class="col-sm-9">
      <strong>
        <%= link_to 'Giochi', games_path %>
        <%= link_to 'Categorie', categories_path %>
        <%= link_to 'Righe di ordine', controller: 'lines' %>
        <%= link_to 'Ordini', orders_path %>
        <%= link_to 'Utenti', utents_path %>

        <%= link_to 'Nuova Riga di ordine', new_line_path %>
      </strong>
    </div>
    <div class="col-sm-3">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">2</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">3</a></li>
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/lines/new.html.erb
<%= form_with scope: :line, url: lines_path, local: true do |form| %>

<% end %>

<div class="new">
  <h1>Aggiungi una riga di ordine</h1>

  <%= render 'form' %>

</div>


<div class="link"><strong>
  <%= link_to 'Righe di ordine', lines_path  %>
  </strong>
</div>

app/views/lines/show.html.erb
<div class="new">

  <p>
    <strong>Ordine:</strong>
    <%= @line.order_id %>
  </p>

  <p>
    <strong>Gioco:</strong>
    <%= @line.game_id %>
  </p>
  <p>
    <strong>Quantita:</strong>
    <%= @line.quantita %>
  </p>
  <p>
    <strong>Prezzo:</strong>
    <%= @line.prezzo %>
  </p>

</div>

<div class="link"><strong>
  <%= link_to 'Righe di ordine', lines_path  %>
  <%= link_to 'Nuova riga', new_line_path %>
  <%= link_to 'Modifica la riga', edit_line_path(@line) %>
  <%= link_to 'Elimina la riga', line_path(@line),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </strong>
</div>

app/views/orders/_form.html.erb
<%= form_with model: @order, local: true do |form| %>

  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row with_zero_margin">

    <div class="col-sm-4">
      <p>
        <%= form.label :utente %><br>
        <%= form.text_field :utent_id %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :data %><br>
        <%= form.text_area :data %>
      </p>
    </div>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>

app/views/orders/edit.html.erb
<%= form_with(model: @order, local: true) do |form| %>

<% end %>

<div class="new">
  <h1>Modifica l'ordine </h1>

  <%= render 'form' %>
</div>

<div class="link"><strong>
  <%= link_to 'Ordini', orders_path  %>
  </strong>
</div>

app/views/orders/index.html.erb
<div class="new">
    <h1>Ordini</h1>

  <table>
    <tr>
      <th>Utente</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td><%= order.utent_id %></td>
        <td><%= order.data %></td>
        <td><%= link_to 'Show', order_path(order) %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order_path(order),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

</div>
<div class="link">
  <div class="row">
    <div class="col-sm-9">
      <strong>
        <%= link_to 'Giochi', games_path %>
        <%= link_to 'Categorie', categories_path %>
        <%= link_to 'Righe di ordine', lines_path %>
        <%= link_to 'Ordini', controller: 'orders' %>
        <%= link_to 'Utenti', utents_path %>

        <%= link_to 'Nuovo Ordine', new_order_path %>
      </strong>
    </div>
    <div class="col-sm-3">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">2</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">3</a></li>
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<%= form_with scope: :order, url: orders_path, local: true do |form| %>

<% end %>

<div class="new">
  <h1>Aggiungi un ordine</h1>

  <%= render 'form' %>

</div>


<div class="link"><strong>
  <%= link_to 'Ordini', orders_path  %>
  </strong>
</div>

app/views/orders/show.html.erb
<div class="new">

  <p>
    <strong>Utente:</strong>
    <%= @order.utent_id %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= @order.data %>
  </p>

</div>

<div class="link"><strong>
  <%= link_to 'Ordini', orders_path  %>
  <%= link_to 'Nuova ordine', new_order_path %>
  <%= link_to 'Modifica l\'ordine', edit_order_path(@order) %>
  <%= link_to 'Elimina l\'ordine', order_path(@order),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </strong>
</div>

app/views/utents/_form.html.erb
<%= form_with model: @utent, local: true do |form| %>

  <% if @utent.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@utent.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @utent.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row with_zero_margin">

    <div class="col-sm-4">
      <p>
        <%= form.label :email %><br>
        <%= form.text_field :email %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :password %><br>
        <%= form.text_area :password %>
      </p>
    </div>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>

app/views/utents/edit.html.erb
<%= form_with(model: @utent, local: true) do |form| %>

<% end %>

<div class="new">
  <h1>Modifica l'utente </h1>

  <%= render 'form' %>
</div>

<div class="link"><strong>
  <%= link_to 'Utenti', utents_path  %>
  </strong>
</div>

app/views/utents/index.html.erb
<div class="new">
    <h1>Utenti</h1>

  <table>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>

    <% @utents.each do |utent| %>
      <tr>
        <td><%= utent.email %></td>
        <td><%= utent.password %></td>
        <td><%= link_to 'Show', utent_path(utent) %></td>
        <td><%= link_to 'Edit', edit_utent_path(utent) %></td>
        <td><%= link_to 'Destroy', utent_path(utent),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

</div>
<div class="link">
  <div class="row">
    <div class="col-sm-9">
      <strong>
        <%= link_to 'Giochi', games_path %>
        <%= link_to 'Categorie', categories_path %>
        <%= link_to 'Righe di ordine', lines_path %>
        <%= link_to 'Ordini', orders_path %>
        <%= link_to 'Utenti', controller: 'utents' %>

        <%= link_to 'Nuovo Utente', new_utent_path %>
      </strong>
    </div>
    <div class="col-sm-3">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">2</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">3</a></li>
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/utents/new.html.erb
<%= form_with scope: :utent, url: utents_path, local: true do |form| %>

<% end %>

<div class="new">
  <h1>Aggiungi un utente</h1>

  <%= render 'form' %>

</div>


<div class="link"><strong>
  <%= link_to 'Utenti', utents_path  %>
  </strong>
</div>

app/views/utents/show.html.erb
<div class="new">

  <p>
    <strong>Email:</strong>
    <%= @utent.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= @utent.password %>
  </p>

</div>

<div class="link"><strong>
  <%= link_to 'Utenti', utents_path  %>
  <%= link_to 'Nuovo utente', new_utent_path %>
  <%= link_to 'Modifica l\'utente', edit_utent_path(@utent) %>
  <%= link_to 'Elimina l\'utente', utent_path(@utent),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </strong>
</div>