config/routes.rb
Rails.application.routes.draw do

  get 'acquisto/index'
  get 'carrello/index'
  get 'login/index'
  get 'home/index'


  resources :games
  resources :categories
  resources :utents
  resources :orders
  resources :lines

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :games
    validates :nome_cat, presence: true, length: { minimum: 5 }
    validates :descr, presence: true,  length: { maximum: 300 }
    validates :img1, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :category
  has_many :lines
  validates :nome, presence: true, length: { minimum: 5 }
  validates :descr, presence: true,  length: { maximum: 300 }
  validates :img1, presence: true
  validates :img2, presence: true
  validates :img3, presence: true
  validates :prezzo, presence: true

end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :game
  validates :quantita, presence: true
  validates :prezzo, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  has_one :line
  belongs_to :utent
  validates :data, presence: true
end

app/models/utent.rb
class Utent < ApplicationRecord
    has_many :orders
    has_many :lines, through: :orders
    validates :email, presence: true, length: { minimum: 11 }
    validates :password, presence: true,  length: { minimum: 8 }

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

 def create
   @category = Category.new(category_params)

  if @category.save
    redirect_to @category
  else
    render 'new'
  end
 end

def update
 @category = Category.find(params[:id])

 if @category.update(category_params)
   redirect_to @category
 else
   render 'edit'
 end
end

def destroy
  @category = Category.find(params[:id])
  @category.destroy

  redirect_to categories_path
end

private
  def category_params
    params.require(:category).permit(:nome_cat,:descr,:img1)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

 def create
   @game = Game.new(game_params)

  if @game.save
    redirect_to @game
  else
    render 'new'
  end
 end

def update
 @game = Game.find(params[:id])

 if @game.update(game_params)
   redirect_to @game
 else
   render 'edit'
 end
end

def destroy
  @game = Game.find(params[:id])
  @game.destroy

  redirect_to games_path
end

private
  def game_params
    params.require(:game).permit(:nome,:descr,:category_id,:img1,:img2,:img3,:prezzo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @lines = Line.all
  end

  def show
    @line = Line.find(params[:id])
  end

  def new
    @line = Line.new
  end

  def edit
    @line = Line.find(params[:id])
  end

 def create
   @line = Line.new(line_params)

  if @line.save
    redirect_to @line
  else
    render 'new'
  end
 end

def update
 @line = Line.find(params[:id])

 if @line.update(line_params)
   redirect_to @line
 else
   render 'edit'
 end
end

def destroy
  @line = Line.find(params[:id])
  @line.destroy

  redirect_to lines_path
end

private
  def line_params
    params.require(:line).permit(:order_id,:game_id,:quantita,:prezzo)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

 def create
   @order = Order.new(order_params)

  if @order.save
    redirect_to @order
  else
    render 'new'
  end
 end

def update
 @order = Order.find(params[:id])

 if @order.update(order_params)
   redirect_to @order
 else
   render 'edit'
 end
end

def destroy
  @order = Order.find(params[:id])
  @order.destroy

  redirect_to orders_path
end

private
  def order_params
    params.require(:order).permit(:data,:utent_id)
  end
end

app/controllers/utents_controller.rb
class UtentsController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @utents = Utent.all
  end

  def show
    @utent = Utent.find(params[:id])
  end

  def new
    @utent = Utent.new
  end

  def edit
    @utent = Utent.find(params[:id])
  end

 def create
   @utent = Utent.new(utent_params)

  if @utent.save
    redirect_to @utent
  else
    render 'new'
  end
 end

def update
 @utent = Utent.find(params[:id])

 if @utent.update(utent_params)
   redirect_to @utent
 else
   render 'edit'
 end
end

def destroy
  @utent = Utent.find(params[:id])
  @utent.destroy

  redirect_to utents_path
end

private
  def utent_params
    params.require(:utent).permit(:email,:password)
  end
end

app/helpers/acquisto_helper.rb
module AcquistoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carrello_helper.rb
module CarrelloHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/utents_helper.rb
module UtentsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |form| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row with_zero_margin">

    <div class="col-sm-4">
      <p>
        <%= form.label :nome_cat %><br>
        <%= form.text_field :nome_cat %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :descrizione %><br>
        <%= form.text_area :descr %>
      </p>
    </div>

    <div class="col-sm-4">
      <p>
        <%= form.label :immagine1 %><br>
        <%= form.text_area :img1 %>
      </p>
    </div>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>

app/views/categories/edit.html.erb
<%= form_with(model: @category, local: true) do |form| %>

<% end %>

<div class="new">
  <h1>Modifica la categoria </h1>

  <%= render 'form' %>
</div>

<div class="link"><strong>
  <%= link_to 'Giochi', categories_path  %>
  </strong>
</div>

app/views/categories/index.html.erb
<div class="new">
  <h1>Categorie</h1>

  <table>
    <tr>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th>Immagine1</th>
      <th colspan="3"></th>
    </tr>

    <% @categories.each do |category| %>
      <tr>
        <td><%= category.nome_cat %></td>
        <td><%= category.descr %></td>
        <td><%= category.img1 %></td>
        <td><%= link_to 'Show', category_path(category) %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

</div>
<div class="link">
  <div class="row">
    <div class="col-sm-9">
      <strong>
        <%= link_to 'Giochi', games_path %>
        <%= link_to 'Categorie', controller: 'categories' %>
        <%= link_to 'Righe di ordine', lines_path %>
        <%= link_to 'Ordini', orders_path %>
        <%= link_to 'Utenti', utents_path %>

        <%= link_to 'Nuova Categoria', new_category_path %>
      </strong>
    </div>
    <div class="col-sm-3">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">2</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">3</a></li>
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= form_with scope: :category, url: categories_path, local: true do |form| %>

<% end %>

<div class="new">
  <h1>Aggiungi una categoria</h1>

  <%= render 'form' %>

</div>


<div class="link"><strong>
  <%= link_to 'Categorie', categories_path  %>
  </strong>
</div>

app/views/categories/show.html.erb
<div class="new">

  <p>
    <strong>Nome:</strong>
    <%= @category.nome_cat %>
  </p>

  <p>
    <strong>Descrizione:</strong>
    <%= @category.descr %>
  </p>
  <p>
    <strong>Immagine1:</strong>
    <%= @category.img1 %>
  </p>

</div>

<div class="link"><strong>
  <%= link_to 'Categorie', categories_path  %>
  <%= link_to 'Nuova categoria', new_category_path %>
  <%= link_to 'Modifica la categoria', edit_category_path(@category) %>
  <%= link_to 'Elimina la categoria', category_path(@category),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </strong>
</div>