config/routes.rb
Rails.application.routes.draw do

  get 'acquisto/index'
  get 'carrello/index'
  get 'login/index'
  get 'home/index'


  resources :games
  resources :categories
  resources :utents
  resources :orders
  resources :lines

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :games
    validates :nome_cat, presence: true, length: { minimum: 5 }
    validates :descr, presence: true,  length: { maximum: 300 }
    validates :img1, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :category
  has_many :lines
  validates :nome, presence: true, length: { minimum: 5 }
  validates :descr, presence: true,  length: { maximum: 300 }
  validates :img1, presence: true
  validates :img2, presence: true
  validates :img3, presence: true
  validates :prezzo, presence: true

end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :game
  validates :quantita, presence: true
  validates :prezzo, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  has_one :line
  belongs_to :utent
  validates :data, presence: true
end

app/models/utent.rb
class Utent < ApplicationRecord
    has_many :orders
    has_many :lines, through: :orders
    validates :email, presence: true, length: { minimum: 11 }
    validates :password, presence: true,  length: { minimum: 8 }

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

 def create
   @game = Game.new(game_params)

  if @game.save
    redirect_to @game
  else
    render 'new'
  end
 end

def update
 @game = Game.find(params[:id])

 if @game.update(game_params)
   redirect_to @game
 else
   render 'edit'
 end
end

def destroy
  @game = Game.find(params[:id])
  @game.destroy

  redirect_to games_path
end

private
  def game_params
    params.require(:game).permit(:nome,:descr,:category_id,:img1,:img2,:img3,:prezzo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
    http_basic_authenticate_with name: "tooks", password: "818"
  def index
    @lines = Line.all
  end

  def show
    @line = Line.find(params[:id])
  end

  def new
    @line = Line.new
  end

  def edit
    @line = Line.find(params[:id])
  end

 def create
   @line = Line.new(line_params)

  if @line.save
    redirect_to @line
  else
    render 'new'
  end
 end

def update
 @line = Line.find(params[:id])

 if @line.update(line_params)
   redirect_to @line
 else
   render 'edit'
 end
end

def destroy
  @line = Line.find(params[:id])
  @line.destroy

  redirect_to lines_path
end

private
  def line_params
    params.require(:line).permit(:order_id,:game_id,:quantita,:prezzo)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/helpers/acquisto_helper.rb
module AcquistoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carrello_helper.rb
module CarrelloHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/utents_helper.rb
module UtentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
  <head>
    <title>Tooks</title>
    <!-- Required meta tags -->
    <link rel="icon" type="image/jpg" href="/assets/tooks.jpg">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class=" navbar navbar-expand-md navbar-black bg-black fixed-top barra">
      <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1"
          aria-expanded="false" aria-label="Toggle navigation"><span class="dark-blue-text"><i class="fa fa-bars fa-1x"></i></span></button>

      <div class=" hamburger" onclick="myFunction(this)">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
      </div>

      <a class=" navbar-brand">
        <h2><%= link_to 'Tooks', home_index_path %></h2>
        <%= image_tag "tooks.jpg", size: "40x40" %>
      </a>

      <div class=" collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" style="padding-top:0px;"><h4><%= link_to 'Carrello', carrello_index_path%></h4></a>
          </li>
          <li class="nav-item">
              <a class="nav-link" style="padding-top:0px;"><h4><%= link_to 'Accedi', login_index_path %></h4></a>
          </li>
        </ul>
      </div>

    </nav>




    <!-- Collapsible content -->

    <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <div class="row">
        <div class="col-sm-3 menu_hamburger" >
          <h3>Categorie</h3>
          <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Sport
              <span class="badge badge-primary badge-pill">14</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Azione
              <span class="badge badge-primary badge-pill">27</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Avventura
              <span class="badge badge-primary badge-pill">51</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Sparatutto
              <span class="badge badge-primary badge-pill">23</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Horror
              <span class="badge badge-primary badge-pill">16</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Istruzione
              <span class="badge badge-primary badge-pill">11</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Strategia
              <span class="badge badge-primary badge-pill">18</span>
            </li>
          </ul>
        </div>
      </div>

    </div>

    <%= yield %>

    <div class="footer"></div>
    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>